import React from 'react';
import { ReportData, TaskItem } from '../types';
import { BarChart2 } from 'lucide-react';

interface Props {
  data: ReportData;
  onChange?: (updatedData: ReportData) => void;
}

export const DocumentPage2: React.FC<Props> = ({ data, onChange }) => {
  // Ensure we have a primary task object representing this week's progress
  const primaryTask: TaskItem = data.tasks && data.tasks.length > 0
    ? data.tasks[0]
    : {
        id: 'task-1',
        no: 1,
        description: '',
        weightPercent: 100,
        prevPercent: 0,
        thisWeekPercent: 0,
        accumulatedPercent: 0,
        totalPercent: 0,
      };

  // Auto-generate multi-line work summary from daily logs
  const dailyDetailsList = (data.dailyLogs || [])
    .filter((log) => log.details && log.details.trim() !== '')
    .map((log, i) => {
      const dateTag = log.shortDateStr || log.dateStr || `วันที่ ${i + 1}`;
      return `${dateTag}: ${log.details.trim()}`;
    });

  const autoGeneratedDescription = dailyDetailsList.length > 0
    ? dailyDetailsList.join('\n')
    : (primaryTask.description || '');

  const handleUpdatePrimaryTask = (field: keyof TaskItem, value: any) => {
    if (!onChange) return;
    
    let updatedTasks = [...(data.tasks || [])];
    if (updatedTasks.length === 0) {
      updatedTasks = [{
        id: 'task-1',
        no: 1,
        description: autoGeneratedDescription,
        weightPercent: 0,
        prevPercent: 0,
        thisWeekPercent: 0,
        accumulatedPercent: 0,
        totalPercent: 0,
      }];
    }

    if (field === 'weightPercent') {
      const weight = typeof value === 'number' ? value : (parseFloat(value) || 0);
      const prevP = updatedTasks[0].prevPercent || 0;
      const thisW = weight; // ในสัปดาห์ = สัดส่วนของงาน%
      const accum = Number((prevP + thisW).toFixed(2)); // สะสม = ถึงสัปดาห์ก่อน + ในสัปดาห์
      const total = accum; // ผลงานรวม% = สะสม

      updatedTasks[0] = {
        ...updatedTasks[0],
        weightPercent: weight,
        thisWeekPercent: thisW,
        accumulatedPercent: accum,
        totalPercent: total,
        description: autoGeneratedDescription,
      };
    } else {
      updatedTasks[0] = {
        ...updatedTasks[0],
        [field]: value,
        description: autoGeneratedDescription,
      };
    }

    onChange({ ...data, tasks: updatedTasks });
  };

  const updateField = (field: keyof ReportData, value: any) => {
    if (onChange) {
      onChange({ ...data, [field]: value });
    }
  };

  const formatNum = (val: number | undefined | null) => {
    if (val === undefined || val === null || val === 0) return '-';
    return Number.isInteger(val) ? String(val) : String(Number(val.toFixed(2)));
  };

  return (
    <div>
      {/* Screen View: Dark Neumorphism Form */}
      <div className="print:hidden space-y-6">
        
        {/* Table Card */}
        <div className="neu-flat p-6 rounded-3xl border border-white/5 space-y-4">
          <div className="flex items-center gap-3 border-b border-white/5 pb-4 mb-2">
            <div className="w-10 h-10 rounded-xl neu-pressed flex items-center justify-center text-orange-400 border border-orange-500/20">
              <BarChart2 className="w-5 h-5" />
            </div>
            <div>
              <h2 className="font-bold text-lg text-orange-400 tracking-wide">
                ผลการดำเนินงานในสัปดาห์
              </h2>
              <p className="text-xs text-gray-400 mt-0.5">
                บันทึกผลงานประจำสัปดาห์ (งานที่ดำเนินการดึงจากบันทึกรายวันอัตโนมัติ)
              </p>
            </div>
          </div>

          <div className="overflow-x-auto pb-4">
            <div className="min-w-[800px]">
              {/* Table Header */}
              <div className="flex text-xs font-bold text-gray-400 text-center gap-2 mb-2 items-end">
                <div className="w-12 py-2 neu-pressed rounded-xl border border-white/5 flex-shrink-0">
                  ที่
                </div>
                <div className="flex-1 py-2 neu-pressed rounded-xl border border-white/5">
                  งานที่ดำเนินการ
                </div>
                <div className="w-20 py-2 neu-pressed rounded-xl border border-white/5 flex-shrink-0 leading-tight">
                  สัดส่วนของ<br/>งาน%
                </div>
                <div className="flex flex-col w-52 gap-1 flex-shrink-0">
                  <div className="py-1 neu-pressed rounded-xl border border-white/5">
                    ผลงาน%
                  </div>
                  <div className="flex gap-1">
                    <div className="flex-1 py-2 neu-pressed rounded-xl border border-white/5 leading-tight">
                      ถึงสัปดาห์<br/>ก่อน
                    </div>
                    <div className="flex-1 py-2 neu-pressed rounded-xl border border-white/5 leading-tight">
                      ในสัปดาห์
                    </div>
                    <div className="flex-1 py-2 neu-pressed rounded-xl border border-white/5 leading-tight">
                      สะสม
                    </div>
                  </div>
                </div>
                <div className="w-20 py-2 neu-pressed rounded-xl border border-white/5 flex-shrink-0 leading-tight">
                  ผลงานรวม<br/>%
                </div>
              </div>

              {/* Single Data Row */}
              <div className="flex gap-2 items-start text-sm my-2">
                {/* ที่ - Week No read only */}
                <div className="w-12 h-11 flex items-center justify-center text-gray-300 font-semibold flex-shrink-0 neu-pressed rounded-xl border border-white/5 text-sm">
                  {data.weekNo || '1'}
                </div>

                {/* งานที่ดำเนินการ - Multi-line auto-generate preview box (read-only) */}
                <div className="flex-1 neu-pressed border border-white/5 rounded-xl px-3.5 py-2.5 text-xs sm:text-sm text-gray-200 min-h-[72px] flex flex-col justify-start select-none cursor-default">
                  {dailyDetailsList.length > 0 ? (
                    <div className="space-y-1.5 py-1">
                      {dailyDetailsList.map((item, idx) => {
                        const colonIdx = item.indexOf(':');
                        const prefix = colonIdx !== -1 ? item.substring(0, colonIdx) : '';
                        const content = colonIdx !== -1 ? item.substring(colonIdx + 1) : item;
                        return (
                          <div key={idx} className="leading-relaxed text-gray-300">
                            {prefix && <span className="text-gray-400 font-semibold">{prefix}:</span>}
                            <span className="ml-1.5">{content}</span>
                          </div>
                        );
                      })}
                    </div>
                  ) : (
                    <span className="text-gray-500 italic text-xs py-2">
                      (ดึงข้อมูลจากบันทึกรายวันอัตโนมัติ — หากต้องการแก้ไขให้ระบุในตารางบันทึกรายวัน)
                    </span>
                  )}
                </div>

                {/* สัดส่วนของงาน% - Input */}
                <div className="w-20 flex-shrink-0">
                  <input
                    type="number"
                    value={primaryTask.weightPercent !== undefined && primaryTask.weightPercent !== null ? (primaryTask.weightPercent === 0 ? '' : primaryTask.weightPercent) : ''}
                    onChange={(e) => handleUpdatePrimaryTask('weightPercent', parseFloat(e.target.value) || 0)}
                    placeholder="0"
                    className="w-full h-11 text-center neu-pressed border border-white/5 rounded-xl px-2 text-white font-semibold focus:outline-none focus:border-orange-500/50 transition-colors"
                  />
                </div>

                {/* ผลงาน% 3 ช่อง */}
                <div className="flex w-52 gap-1 flex-shrink-0">
                  {/* ถึงสัปดาห์ก่อน - Read-only display */}
                  <div className="flex-1 h-11 text-center text-gray-400 font-semibold px-1 text-xs sm:text-sm flex items-center justify-center neu-pressed rounded-xl border border-white/5" title="ผลงานสะสมถึงสัปดาห์ก่อน">
                    {formatNum(primaryTask.prevPercent)}
                  </div>

                  {/* ในสัปดาห์ - Auto-calculated read-only display */}
                  <div className="flex-1 h-11 text-center text-gray-300 font-semibold px-1 text-xs sm:text-sm flex items-center justify-center neu-pressed rounded-xl border border-white/5" title="คำนวณอัตโนมัติตามสัดส่วนของงาน%">
                    {formatNum(primaryTask.thisWeekPercent)}
                  </div>

                  {/* สะสม - Read-only display */}
                  <div className="flex-1 h-11 text-center text-gray-300 font-semibold px-1 text-xs sm:text-sm flex items-center justify-center neu-pressed rounded-xl border border-white/5" title="ผลงานสะสม (ถึงสัปดาห์ก่อน + ในสัปดาห์)">
                    {formatNum(primaryTask.accumulatedPercent)}
                  </div>
                </div>

                {/* ผลงานรวม% - Auto-calculated read-only display */}
                <div className="w-20 flex-shrink-0 h-11 text-center text-gray-300 font-semibold px-2 text-xs sm:text-sm flex items-center justify-center neu-pressed rounded-xl border border-white/5" title="ผลงานรวมสะสม%">
                  {formatNum(primaryTask.totalPercent)}
                </div>
              </div>

              {/* Summary Row */}
              <div className="flex gap-2 items-center text-sm pt-4 border-t border-white/5">
                <div className="w-12 flex-shrink-0"></div>
                <div className="flex-1"></div>
                <div className="w-20 text-center text-gray-300 font-bold neu-pressed py-2.5 rounded-xl border border-white/5 flex-shrink-0">
                  {formatNum(primaryTask.weightPercent)}
                </div>
                <div className="w-52 text-center text-gray-300 font-bold neu-pressed py-2.5 rounded-xl border border-white/5 flex-shrink-0 tracking-wider">
                  รวม
                </div>
                <div className="w-20 text-center text-gray-300 font-bold neu-pressed py-2.5 rounded-xl border border-white/5 flex-shrink-0">
                  {formatNum(primaryTask.totalPercent)}
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

      {/* Print View: Document format */}
      <div className="hidden print:flex bg-white text-black p-8 sm:p-12 shadow-none font-sarabun max-w-[210mm] min-h-[297mm] mx-auto text-[15px] leading-relaxed relative flex-col justify-between select-text">
        <div>
          {/* Title */}
          <h2 className="text-base font-bold mb-3">ผลการดำเนินงานในสัปดาห์</h2>

          {/* Table */}
          <div className="overflow-x-auto">
            <table className="w-full border-collapse border border-black text-center text-[13px] leading-tight">
              <thead>
                <tr className="bg-gray-50">
                  <th rowSpan={2} className="border border-black p-2 font-bold w-[6%]">
                    ที่
                  </th>
                  <th rowSpan={2} className="border border-black p-2 font-bold w-[42%] text-center">
                    งานที่ดำเนินการ
                  </th>
                  <th rowSpan={2} className="border border-black p-2 font-bold w-[12%]">
                    สัดส่วนของงาน%
                  </th>
                  <th colSpan={3} className="border border-black p-1.5 font-bold">
                    ผลงาน%
                  </th>
                  <th rowSpan={2} className="border border-black p-2 font-bold w-[12%]">
                    ผลงานรวม%
                  </th>
                </tr>
                <tr className="bg-gray-50 text-[12px]">
                  <th className="border border-black p-1.5 font-bold w-[12%] leading-normal">
                    ถึงสัปดาห์ก่อน
                  </th>
                  <th className="border border-black p-1.5 font-bold w-[12%] leading-normal">
                    ในสัปดาห์
                  </th>
                  <th className="border border-black p-1.5 font-bold w-[12%] leading-normal">
                    สะสม
                  </th>
                </tr>
              </thead>
              <tbody>
                {/* 1 Main Weekly Task Row */}
                <tr className="min-h-[44px]">
                  <td className="border border-black p-2 align-top font-bold">
                    {data.weekNo || '1'}
                  </td>
                  <td className="border border-black p-2 align-top text-left font-medium whitespace-pre-line leading-relaxed">
                    {autoGeneratedDescription || 'ไม่ปฏิบัติงาน'}
                  </td>
                  <td className="border border-black p-2 align-top font-medium">
                    {formatNum(primaryTask.weightPercent)}
                  </td>
                  <td className="border border-black p-2 align-top font-medium">
                    {formatNum(primaryTask.prevPercent)}
                  </td>
                  <td className="border border-black p-2 align-top font-medium">
                    {formatNum(primaryTask.thisWeekPercent)}
                  </td>
                  <td className="border border-black p-2 align-top font-medium">
                    {formatNum(primaryTask.accumulatedPercent)}
                  </td>
                  <td className="border border-black p-2 align-top font-medium">
                    {formatNum(primaryTask.totalPercent)}
                  </td>
                </tr>

                {/* Summary Total Row */}
                <tr className="font-bold bg-gray-50 h-9">
                  <td className="border border-black p-2"></td>
                  <td className="border border-black p-2"></td>
                  <td className="border border-black p-2">
                    {formatNum(primaryTask.weightPercent)}
                  </td>
                  <td colSpan={3} className="border border-black p-2 text-center font-bold">
                    รวม
                  </td>
                  <td className="border border-black p-2">
                    {formatNum(primaryTask.totalPercent)}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};
